# Generated by Django 5.2.6 on 2025-09-24 23:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_biblioteca', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_lector', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre_lector', models.CharField(max_length=255)),
                ('correo_lector', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('copias', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fisico', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(null=True)),
                ('fecha_retorno', models.DateTimeField(null=True)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.libro')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.tipocategoria'),
        ),
    ]
