# Generated by Django 4.2.25 on 2025-10-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_categoria_tipocategoria_autor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
