# Generated by Django 5.2.7 on 2025-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0003_autor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='web',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
