# Generated by Django 5.2.7 on 2025-11-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0004_alter_biblioteca_web_alter_comuna_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='codigo',
            new_name='codigo_comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='nombre_comuna',
        ),
    ]
