# Generated by Django 5.2.7 on 2025-11-06 03:46

import datetime
import primera_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0005_rename_codigo_comuna_codigo_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), validators=[primera_app.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lector',
            name='correo_lector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=9, unique=True, validators=[primera_app.models.validar_rut]),
        ),
    ]
