# Generated by Django 5.2.7 on 2025-11-06 04:34

import primera_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0006_lector_fecha_nacimiento_alter_autor_pseudonimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=None, validators=[primera_app.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[primera_app.models.validar_rut]),
        ),
    ]
