# Generated by Django 5.2.7 on 2025-11-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0007_lector_genero_alter_lector_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
    ]
